title: "Estatística Aplicada a Ciências Ambientais"
description: "A brief description of your website"
url: "https://your-username.github.io"
theme: jekyll-theme-cayman  # Example theme, choose the one you want
